apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-01
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-data-01"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-02
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-data-02"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-03
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-data-03"
