apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-server
  namespace: monitor
  labels:
    app: grafana-server
spec:
  selector:
      matchLabels:
        app: grafana-server # has to match .spec.template.metadata.labels
  serviceName: "grafana-server-svc"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
        - name: grafana-server
          image: grafana/grafana
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
            limits:
              cpu: "0.2"
              memory: "1Gi"
          volumeMounts:
          - mountPath: /var/lib/grafana
            subPath: grafana
            name: grafana-storage
  volumeClaimTemplates:
  - metadata:
      name: grafana-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-server-svc
  namespace: monitor
  labels:
    app: grafana-server
spec:
  type: ClusterIP
  selector:
    app: grafana-server
  ports:
    - port: 3000
      targetPort: 3000