# 创建一个local类型的存储卷
# https://kubernetes.io/zh/docs/concepts/storage/volumes/#local
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data-01
  namespace: coletaconsciente
  labels:
    app: grafana
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/data/grafana-data-01
  # 使用节点亲和性nodeAffinity保证被正确调度到对应的节点
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master-node1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-01
  namespace: coletaconsciente
  labels:
    app: prometheus
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/data/prometheus-data-01
  # 使用节点亲和性nodeAffinity保证被正确调度到对应的节点
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master-node1