apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-nginx-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`www.woaisok8s.com`)
      kind: Rule
      services:
        - name: nginx
          port: 80