apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongodb
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`mongo.woaisok8s.com`)
    services:
    - name: mongodb
      port: 27017