apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: traefik-mongodb-route
spec:
  entryPoints:
    - mongo
  routes:
    - match: HostSNI(`mongo.woaisok8s.com`)
      kind: Rule
      services:
        - name: mongodb
          port: 27017