apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  selector:
    matchLabels:
      app: redmine
  serviceName: "redmine-svc"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        env:
          - name: REDMINE_DB_MYSQL
            value: mysql-0.mysql
          - name: REDMINE_DB_USERNAME
            value: root
          - name: REDMINE_DB_PASSWORD
            value: ''
          - name: REDMINE_DB_DATABASE
            value: redminedb
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: redmine-store
          mountPath: /usr/src/redmine/files
          subPath: files
        - name: redmine-store
          mountPath: /usr/src/redmine/public/themes/PurpleMine2
          subPath: theme/PurpleMine2
  volumeClaimTemplates:
  - metadata:
      name: redmine-store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 1Gi